
services:
  api_flask_usuarios:
    container_name: api_flask_usuarios
    image: apiflaskusuarios/flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:12345@flask_db:5432/flaskapi
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flaskapi
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}