
services:
  api_flask:
    container_name: api_flask
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:12345@api_db:5432/postgres
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    command: flask --app run run -h 0.0.0.0