
services:
  api_flask:
    container_name: api_flask
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:12345@db:5432/postgres
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    command: flask --app run run -h 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: {}